version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-store
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis-store
    ports:
      - 6500:6379
    volumes:
      - redis_data:/data

  store:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: store
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/store
      SPRING_REDIS_URL: redis://redis:6379
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - redis

volumes:
  mongodb_data:
  redis_data: