version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-store
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis-store
    ports:
      - 6500:6379
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: